---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: secure-video
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /mnt/data/mongodb
    type: DirectoryOrCreate

---
# ไม่ต้องใช้ก้ได้ เพราะstatefulsetจะสร้างpvcเอง
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongodb-pvc
#   namespace: secure-video
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#   storageClassName: standard