services:

  elastic-agent:
    image: docker.elastic.co/elastic-agent/elastic-agent:8.14.1
    container_name: elastic-agent3
    user: root
    restart: always

    environment:
      - FLEET_ENROLL=1
      - FLEET_URL=https://315d8352573d457bb3aaf3f55c8e9dd1.fleet.ap-southeast-1.aws.found.io:443
      - FLEET_ENROLLMENT_TOKEN=X0s2YklKNEJ0aC1CZjZTa0plYkk6S0s0eHlGRVUwOXU3SFA5WmprUkhUQQ==
      - FLEET_INSECURE=false

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    networks:
      - secure-video-network
    privileged: true
networks:
  secure-video-network:
    driver: bridge
volumes:
  elastic-agent-data1new1: