services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    # ถอดโหมด Dev ออกทั้งหมด และเอาไฟล์คอนฟิกไปใส่แทน
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      # เมาท์ไฟล์คอนฟิกจากเครื่องของเราเข้าไปในคอนเทนเนอร์
      - ./vault-config.hcl:/vault/config/vault-config.hcl
    networks:
      - secure-video-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "--no-check-certificate", "http://127.0.0.1:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault-secrets-init:
      image: busybox
      container_name: vault-secrets-init
      restart: "no"
      # เพิ่มคำสั่ง chown สิทธิ์ฝั่ง /vault/data ให้เป็นของ user vault (UID 100)
      command: >
        sh -c "chown -R 100:1001 /vault/secrets && chmod 750 /vault/secrets &&
              chown -R 100:1000 /vault/data && chmod 750 /vault/data &&
              echo 'All permissions fixed!'&&
               exit 0"
      volumes:
        - vault-agent-secretsja:/vault/secrets
        - vault_data:/vault/data # ← เมาท์วอลลุ่มของตู้หลักเข้ามาซ่อมสิทธิ์ด้วย
      networks:
        - secure-video-network

  vault-agent:
      image: hashicorp/vault:1.15
      container_name: vault-agent
      restart: unless-stopped
      entrypoint: ["/bin/sh", "/vault/entrypoint.sh"]
      environment:
        VAULT_ADDR: http://vault:8200
        VAULT_ROLE_ID: "${VAULT_ROLE_ID}"
        VAULT_SECRET_ID: "${VAULT_SECRET_ID}"
      # user: root ← เอาบรรทัดนี้ออก เพื่อให้รันเป็นสิทธิ์ user 'vault' (UID 100) ปลอดภัยกว่า
      volumes:
        - ./vault/entrypoint.sh:/vault/entrypoint.sh:ro
        - ./vault/agent.hcl:/vault/config/agent.hcl:ro
        - ./vault/templates:/vault/templates:ro
        - vault-agent-secretsja:/vault/secrets
      networks:
        - secure-video-network
      depends_on:
        vault:
          condition: service_healthy
        vault-secrets-init:
          condition: service_completed_successfully
      cap_add:
        - IPC_LOCK
networks:
  secure-video-network:
    driver: bridge


volumes:
  vault_data:
  vault-agent-secretsja: