version: '3.9'

services:
  pf-host-agent:
    image: docker.elastic.co/observability/profiling-agent:9.4.1
    container_name: pf-host-agent
    env_file:
      - ./BackEnd/.env
    privileged: true
    pid: host
    restart: always
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /var/run/docker.sock:/var/run/docker.sock

      # ✅ เพิ่ม containerd socket — ให้ agent อ่าน Docker labels ได้
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock:ro
      - /var/run/docker/containerd/containerd.sock:/var/run/docker/containerd/containerd.sock:ro

      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /sys/fs/bpf:/sys/fs/bpf:ro
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - /usr/lib/debug:/usr/lib/debug:ro
      - /lib/modules:/lib/modules:ro
    # command: >
    #       /root/pf-host-agent
    #       -project-id=1
    #       -secret-token=HlHQQB8tIWZjl472
    #       -collection-agent=b329e4682f5a4731bb28e4719291303e.profiling.ap-southeast-1.aws.cloud.es.io:443
    #       -probabilistic-threshold=50
    #       -probabilistic-interval=1m
    #       -log-level=error
    command: >
          /root/pf-host-agent
          -project-id=1
          -secret-token=HlHQQB8tIWZjl472
          -collection-agent=b329e4682f5a4731bb28e4719291303e.profiling.ap-southeast-1.aws.cloud.es.io:443
          -probabilistic-threshold=50
          -probabilistic-interval=1m
          -log-level=error    
    networks:
      - secure-video-network

networks:
  secure-video-network:
    driver: bridge