# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import recommendation_pb2 as recommendation__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommended = channel.unary_unary(
                '/recommendation.RecommendationService/GetRecommended',
                request_serializer=recommendation__pb2.RecommendRequest.SerializeToString,
                response_deserializer=recommendation__pb2.VideoListResponse.FromString,
                _registered_method=True)
        self.GetTrending = channel.unary_unary(
                '/recommendation.RecommendationService/GetTrending',
                request_serializer=recommendation__pb2.TrendingRequest.SerializeToString,
                response_deserializer=recommendation__pb2.VideoListResponse.FromString,
                _registered_method=True)
        self.GetCoWatch = channel.unary_unary(
                '/recommendation.RecommendationService/GetCoWatch',
                request_serializer=recommendation__pb2.CoWatchRequest.SerializeToString,
                response_deserializer=recommendation__pb2.CoWatchResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRecommended(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrending(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCoWatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommended': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommended,
                    request_deserializer=recommendation__pb2.RecommendRequest.FromString,
                    response_serializer=recommendation__pb2.VideoListResponse.SerializeToString,
            ),
            'GetTrending': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrending,
                    request_deserializer=recommendation__pb2.TrendingRequest.FromString,
                    response_serializer=recommendation__pb2.VideoListResponse.SerializeToString,
            ),
            'GetCoWatch': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCoWatch,
                    request_deserializer=recommendation__pb2.CoWatchRequest.FromString,
                    response_serializer=recommendation__pb2.CoWatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRecommended(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/GetRecommended',
            recommendation__pb2.RecommendRequest.SerializeToString,
            recommendation__pb2.VideoListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrending(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/GetTrending',
            recommendation__pb2.TrendingRequest.SerializeToString,
            recommendation__pb2.VideoListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCoWatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendationService/GetCoWatch',
            recommendation__pb2.CoWatchRequest.SerializeToString,
            recommendation__pb2.CoWatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
