# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recommendation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'recommendation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14recommendation.proto\x12\x0erecommendation\"2\n\x10RecommendRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\" \n\x0fTrendingRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"1\n\x0e\x43oWatchRequest\x12\x10\n\x08video_id\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"E\n\x05Video\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ss_type\x18\x03 \x01(\t\x12\x0c\n\x04tags\x18\x04 \x03(\t\"b\n\x11VideoListResponse\x12%\n\x06videos\x18\x01 \x03(\x0b\x32\x15.recommendation.Video\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x16\n\x0e\x62oost_category\x18\x03 \x01(\t\"8\n\x0f\x43oWatchResponse\x12%\n\x06videos\x18\x01 \x03(\x0b\x32\x15.recommendation.Video2\x90\x02\n\x15RecommendationService\x12U\n\x0eGetRecommended\x12 .recommendation.RecommendRequest\x1a!.recommendation.VideoListResponse\x12Q\n\x0bGetTrending\x12\x1f.recommendation.TrendingRequest\x1a!.recommendation.VideoListResponse\x12M\n\nGetCoWatch\x12\x1e.recommendation.CoWatchRequest\x1a\x1f.recommendation.CoWatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDREQUEST']._serialized_start=40
  _globals['_RECOMMENDREQUEST']._serialized_end=90
  _globals['_TRENDINGREQUEST']._serialized_start=92
  _globals['_TRENDINGREQUEST']._serialized_end=124
  _globals['_COWATCHREQUEST']._serialized_start=126
  _globals['_COWATCHREQUEST']._serialized_end=175
  _globals['_VIDEO']._serialized_start=177
  _globals['_VIDEO']._serialized_end=246
  _globals['_VIDEOLISTRESPONSE']._serialized_start=248
  _globals['_VIDEOLISTRESPONSE']._serialized_end=346
  _globals['_COWATCHRESPONSE']._serialized_start=348
  _globals['_COWATCHRESPONSE']._serialized_end=404
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=407
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=679
# @@protoc_insertion_point(module_scope)
