global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "app:3000"
  - job_name: "kafka"
    static_configs:
      - targets:
          - "kafka-exporter:9308" # พอร์ตมาตรฐานของ Kafka Exporter
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "cadvisor:8080"
  - job_name: 'kafka-ui'
    metrics_path: '/actuator/prometheus' # ต้องระบุ Path นี้
    static_configs:
      - targets: 
          - "kafka-ui:8080" # ใส่ชื่อ container และ port ของ kafka-ui