---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: secure-video
spec:
  encryptedData:
    redis-password: AgC21jPqHYsu56jBvv7Tu58PcU8uYg3yPharZXzVhDoNKpWFyahdJzGYmHKveUJ859Kcgfkn35/ekuL1nftB26aA8T/yHO7z3EwMJ5aGDXkepxiW2X4pdqlZqasfMasu4X8tnUNRQ8/g2xUZCLsqoaNFNqDHcPZQONmvmRsG4EbVoFZFcy8fD89PTpjW34DRr4FGyQLICP1QrYW4v42JM1nVPro+HVKkj2hO4sM6ZVnglQClr27qSvkEhnKUFho1h5vZ1PBChZK/0TaVqiyGKtH59Rj3YSF09inC/Z9JWEFNFa0O9J2t5vpMcMjAt5+DNB/86Guexefxroxbfov4s6Ngm2Itevvn4TUh27BqIThzkFxHu8amxEDsqbhk1mwtrfnfcz9Ag7U0QHAZHSp6jDSXoJM01QWUB3GjK8h1KWFVmQOgg5NtERHwGMWG/IxAPmCbuhRqEsoxvlHX/ESEm2Q/pGpHTOy5DLWfs17LrQ8PDilDZ61bLlU3Z+QlBUAmXZRF6lwzeO+YI9UarFfXrbWCnWCokB5DtX19iZR+B/FIO1lpahGivdIKeUu1zrJA8xAuSTH2NBvZ80tzpKaDvowhH7eS4v3UpktlZZ+TKKq1GsSGD2FapyY6grRS7v3u7jBgT473iTIEsSgKh3c/yO7BQFrSBsItOtBS4Vinf+VEDKjRARi96zHuikDVQpAbYZgR5OY6T3CnHCznWxSVqHEa
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: secure-video
    type: Opaque
