# grafana/datasources/clickhouse.yaml
apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: clickhouse_db
      port: 8123
      username: app_user
      database: app_db
    secureJsonData:
      password: strong_password