apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse_ds          # <--- เพิ่มบรรทัดนี้ เพื่อให้ Dashboard อ้างอิงได้ถูกต้อง
    access: proxy
    jsonData:
      server: clickhouse_db
      port: 9000
      username: app_user
      defaultDatabase: app_db
    secureJsonData:
      password: strong_password